---
- name: "Ensure required parameters are provided."
  ansible.builtin.assert:
    that:
      - legacy_jdk is defined
      - legacy_jdk.java_home is defined
    quiet: true

- name: "Delete JAVA_HOME from target: {{ legacy_jdk.java_home }}."
  ansible.builtin.file:
    path: "{{ legacy_jdk.java_home }}"
    state: absent
